import type { Metadata } from 'next';
import { Inter, Montserrat } from 'next/font/google';
import './globals.css';

// Configure Inter font
import Script from "next/script";
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter' // CSS variable name
});

// Configure Montserrat font
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat' // CSS variable name
});
export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by Onlook'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en" className={`${inter.variable} ${montserrat.variable}`} data-oid="6iv61jp">
            <body className="" data-oid="1ve4tgn">
                {children}
            
                <Script src="/builtwith.js" strategy="afterInteractive" />
            </body>
        </html>;
}